### PR TITLE
Update application.properties

### LINKED ISSUE #5: service urls update
service urls update required

### PR DESCRIPTION
**Pull request by prasadglx**
Modifications completed

### CODE REVIEW

**Review by Anusha-cell — CHANGES_REQUESTED** [review]
Please add comments

**Comment by prasadglx** [comment]
New URL added for Organization level API's

**Review by illaprasad — APPROVED** [review]
Changes looks good for URL's

**Review by Anusha-cell — APPROVED** [review]
Approved

**Comment by illaprasad** [comment]
Merging the PR for URL's

**Pull request merged**
